AddressFormatException: Add InvalidCharacter exception that is thrown when a character is used that is invalid in the encoding.
(cherry picked from commit 15a15ac0247838d5191daef5647221409810930f)
Signed-off-by: HashEngineering <hashengineeringsolutions@gmail.com>