KeyCrypterException: Introduce dedicated InvalidCipherText exception for when a private key or seed is decrypted, the decrypted message is damaged.
Signed-off-by: HashEngineering <hashengineeringsolutions@gmail.com>