AddressFormatException: Add InvalidDataLength exception that is thrown when the data part isn't of the right size.
(cherry picked from commit d55a547740b28c834ba4ef4d115872995d280ae3)
Signed-off-by: HashEngineering <hashengineeringsolutions@gmail.com>