AddressFormatException: Add InvalidPrefix exception that is thrown when the prefix (version) is invalid.
WrongNetwork exception is now a subclass of this class.

(cherry picked from commit 21d65feb28fe91d4859a9ba71f729f6211764b4c)
Signed-off-by: HashEngineering <hashengineeringsolutions@gmail.com>