ScriptError: New error code for use in ScriptException. Script tests use this to assert for specific errors.
This also adds MINIMALDATA tests from Bitcoin Core into script_tests.json.

(cherry picked from commit d8af6b4be7525459ad0f806bd1969151fdb3c0f6)